# Generated by Django 2.0 on 2017-12-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
