# Generated by Django 2.0 on 2017-12-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='biografi',
            field=models.TextField(blank=True),
        ),
    ]
