# Generated by Django 2.0 on 2017-12-27 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_mahasiswa_biografi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pekerjaan',
            name='mahasiswa',
        ),
        migrations.DeleteModel(
            name='Pekerjaan',
        ),
    ]
