# Generated by Django 2.0 on 2017-12-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20171226_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
