# Generated by Django 2.0 on 2017-12-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20171226_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='tgl_lahir',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
