# Generated by Django 2.0 on 2017-12-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_mahasiswa_tgl_lahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='password',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='poto',
            field=models.ImageField(blank=True, default='static/img/foto/no-img.jpg', upload_to='static/img/foto/'),
        ),
    ]
