# Generated by Django 2.0 on 2017-12-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20171227_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='poto',
            field=models.ImageField(default='static/img/foto/no-img.jpg', null=True, upload_to='static/img/foto/'),
        ),
    ]
